# Generated by Django 6.0.4 on 2026-04-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_answer_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('starter_code', models.TextField(blank=True, help_text='Код, который будет показан студенту для начала работы', verbose_name='Начальный код')),
                ('test_code', models.TextField(help_text='Код для проверки решения студента (выполняется на сервере)', verbose_name='Проверочный код')),
                ('points', models.IntegerField(default=10, verbose_name='Баллы')),
                ('order', models.IntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
